//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaCommerce.Umbraco.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeveloperTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeveloperTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeaCommerce.Umbraco.Application.Resources.DeveloperTerms", typeof(DeveloperTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy a license.
        /// </summary>
        public static string BuyALicense {
            get {
                return ResourceManager.GetString("BuyALicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Tea Commerce website.
        /// </summary>
        public static string GoToTheTeaCommerceWebsite {
            get {
                return ResourceManager.GetString("GoToTheTeaCommerceWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tea Commerce successfully installed!.
        /// </summary>
        public static string Installation_Complete {
            get {
                return ResourceManager.GetString("Installation_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the installation.
        /// </summary>
        public static string Installation_StepsToComplete1 {
            get {
                return ResourceManager.GetString("Installation_StepsToComplete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///      For you to finish the installation of Tea Commerce do the following&lt;/p&gt;
        ///    &lt;ol&gt;
        ///      &lt;li&gt;Add the following script in your html &amp;lt;head&amp;gt; tag.
        ///      &lt;/li&gt;
        ///      &lt;li&gt;Go to the Users section and give your user access to the Tea Commerce section
        ///      &lt;/li&gt;
        ///    &lt;/ol&gt;&lt;/p&gt;.
        /// </summary>
        public static string Installation_StepsToComplete2 {
            get {
                return ResourceManager.GetString("Installation_StepsToComplete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help.
        /// </summary>
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision history.
        /// </summary>
        public static string RevisionHistory {
            get {
                return ResourceManager.GetString("RevisionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starter kit package.
        /// </summary>
        public static string StarterKitPackage {
            get {
                return ResourceManager.GetString("StarterKitPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support forum.
        /// </summary>
        public static string SupportForum {
            get {
                return ResourceManager.GetString("SupportForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid domains.
        /// </summary>
        public static string ValidDomains {
            get {
                return ResourceManager.GetString("ValidDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to buy a license.
        /// </summary>
        public static string WantToBuyALicense {
            get {
                return ResourceManager.GetString("WantToBuyALicense", resourceCulture);
            }
        }
    }
}
