//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaCommerce.Umbraco.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentProviderTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentProviderTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeaCommerce.Umbraco.Application.Resources.PaymentProviderTerms", typeof(PaymentProviderTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add setting.
        /// </summary>
        public static string AddSetting {
            get {
                return ResourceManager.GetString("AddSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed API calls.
        /// </summary>
        public static string AllowedApiCalls {
            get {
                return ResourceManager.GetString("AllowedApiCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve order.
        /// </summary>
        public static string ApproveOrder {
            get {
                return ResourceManager.GetString("ApproveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel payment.
        /// </summary>
        public static string CancelPayment {
            get {
                return ResourceManager.GetString("CancelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture payment.
        /// </summary>
        public static string CapturePayment {
            get {
                return ResourceManager.GetString("CapturePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the transaction? The entire amount will be cancelled..
        /// </summary>
        public static string ConfirmPaymentCancel {
            get {
                return ResourceManager.GetString("ConfirmPaymentCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to capture the transaction? The entire amount will be captured..
        /// </summary>
        public static string ConfirmPaymentCapture {
            get {
                return ResourceManager.GetString("ConfirmPaymentCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to refund the transaction? The entire amount will be refunded..
        /// </summary>
        public static string ConfirmPaymentRefund {
            get {
                return ResourceManager.GetString("ConfirmPaymentRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        public static string Finalize {
            get {
                return ResourceManager.GetString("Finalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get status.
        /// </summary>
        public static string GetStatus {
            get {
                return ResourceManager.GetString("GetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to documentation.
        /// </summary>
        public static string LinkToDocumentation {
            get {
                return ResourceManager.GetString("LinkToDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load default settings.
        /// </summary>
        public static string LoadDefaultSettings {
            get {
                return ResourceManager.GetString("LoadDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will replace all your settings.\nAre you sure?.
        /// </summary>
        public static string LoadDefaultSettingsConfirm {
            get {
                return ResourceManager.GetString("LoadDefaultSettingsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment provider.
        /// </summary>
        public static string PaymentProvider {
            get {
                return ResourceManager.GetString("PaymentProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like an error happend with the payment provider - see the log for details.
        /// </summary>
        public static string PaymentProviderError {
            get {
                return ResourceManager.GetString("PaymentProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund payment.
        /// </summary>
        public static string RefundPayment {
            get {
                return ResourceManager.GetString("RefundPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
