//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaCommerce.Umbraco.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeaCommerce.Umbraco.Application.Resources.StoreTerms", typeof(StoreTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed template files for rendering.
        /// </summary>
        public static string AllowedTemplateFilesForRendering {
            get {
                return ResourceManager.GetString("AllowedTemplateFilesForRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the files that can be rendered from the JavaScript.
        /// </summary>
        public static string AllowedTemplateFilesForRenderingHelp {
            get {
                return ResourceManager.GetString("AllowedTemplateFilesForRenderingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart number prefix.
        /// </summary>
        public static string CartNumberPrefix {
            get {
                return ResourceManager.GetString("CartNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation email.
        /// </summary>
        public static string ConfirmationEmailTemplate {
            get {
                return ResourceManager.GetString("ConfirmationEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie timeout.
        /// </summary>
        public static string CookieTimeout {
            get {
                return ResourceManager.GetString("CookieTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout in minutes.
        /// </summary>
        public static string CookieTimeoutHelp {
            get {
                return ResourceManager.GetString("CookieTimeoutHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days to be valid.
        /// </summary>
        public static string DaysValid {
            get {
                return ResourceManager.GetString("DaysValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default country.
        /// </summary>
        public static string DefaultCountry {
            get {
                return ResourceManager.GetString("DefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default order status.
        /// </summary>
        public static string DefaultOrderStatus {
            get {
                return ResourceManager.GetString("DefaultOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default VAT group.
        /// </summary>
        public static string DefaultVatGroup {
            get {
                return ResourceManager.GetString("DefaultVatGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit order UI file.
        /// </summary>
        public static string EditOrderUiFile {
            get {
                return ResourceManager.GetString("EditOrderUiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number prefix.
        /// </summary>
        public static string OrderNumberPrefix {
            get {
                return ResourceManager.GetString("OrderNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment inconsistency email.
        /// </summary>
        public static string PaymentInconsistencyEmailTemplate {
            get {
                return ResourceManager.GetString("PaymentInconsistencyEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices is specified with VAT.
        /// </summary>
        public static string PricesIsSpecifiedWithVat {
            get {
                return ResourceManager.GetString("PricesIsSpecifiedWithVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product property aliases.
        /// </summary>
        public static string ProductPropertyAliases {
            get {
                return ResourceManager.GetString("ProductPropertyAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product uniqueness property aliases.
        /// </summary>
        public static string ProductUniquenessPropertyAliases {
            get {
                return ResourceManager.GetString("ProductUniquenessPropertyAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share stock with.
        /// </summary>
        public static string StockSharingStore {
            get {
                return ResourceManager.GetString("StockSharingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products of both stores will share stock.
        /// </summary>
        public static string StockSharingStoreHelp {
            get {
                return ResourceManager.GetString("StockSharingStoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store saved.
        /// </summary>
        public static string StoreSaved {
            get {
                return ResourceManager.GetString("StoreSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use cookies.
        /// </summary>
        public static string UseCookies {
            get {
                return ResourceManager.GetString("UseCookies", resourceCulture);
            }
        }
    }
}
